export default {
  today: 'Бугун',
  now: 'Энди',
  backToToday: 'Жорий сана',
  ok: 'Ok',
  clear: 'Аниқ',
  month: 'Ой',
  year: 'Йил',
  timeSelect: 'Вақт танланг',
  dateSelect: 'Санани танланг',
  monthSelect: 'Ойни танланг',
  yearSelect: 'Йилни танланг',
  decadeSelect: 'Ўн йилликни танланг',
  yearFormat: 'YYYY',
  dateFormat: 'D-M-YYYY',
  dayFormat: 'D',
  dateTimeFormat: 'D-M-YYYY HH:mm:ss',
  monthBeforeYear: true,
  previousMonth: 'Олдинги ой (PageUp)',
  nextMonth: 'Кeйинги ой (PageDown)',
  previousYear: 'Ўтган йил (Control + left)',
  nextYear: 'Кeйинги йил (Control + right)',
  previousDecade: 'Олдинги ўн йил',
  nextDecade: 'Кeйинги ўн йил',
  previousCentury: 'Олдинги аср',
  nextCentury: 'Кeйинги аср'
};
